# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    target-branch: 'main'
    commit-message:
      # Prefix commit messages with "fix" (to trigger a release from semantic-versioning)
      prefix: fix
      # Prefix devDepedencies commits with "chore" (no release needed)
      prefix-development: chore
      include: scope
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    target-branch: 'main'
