# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
#
# Defaulting to the settings for the `main` branch
[build]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# ##############################
# 'main' branch
# ##############################

# 'main' branch context
[context.main]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# ##############################
# 'legacy' branch
# ##############################

# 'legacy' branch context
[context.legacy]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# Redirect old beta site to the main URL (until we have a new beta for e.g. Vue 4, etc.)
[[redirects]]
  from = "https://beta.kongponents.konghq.com/*"
  to = "https://beta.kongponents.konghq.com/:splat"
  status = 302
