# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
#
# Defaulting to the same settings as the `main` branch
[build]
  base = "/"
  command = "yarn build:styles && yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# ##############################
# 'main' branch
# ##############################

# 'main' branch context
[context.main]
  base = "/"
  command = "yarn build:styles && yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# ##############################
# 'legacy' branch
# ##############################

# 'legacy' branch context
[context.legacy]
  base = "/"
  command = "yarn build:styles && yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# ##############################
# 'beta' branch
# ##############################

# 'beta' branch context
[context.beta]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.15.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }
