# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
#
# Defaulting to the same settings as the `main` branch
[build]
  base = "/"
  command = "yarn build:styles && yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "14.19.1" }

# ##############################
# 'main' branch
# ##############################

# 'main' branch context
[context.main]
  base = "/"
  command = "yarn build:styles && yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "14.19.1" }

# ##############################
# 'next' branch
# ##############################

# 'next' branch context
[context.next]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
  environment = { NODE_VERSION = "16.14.0" }
