# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
#
# Defaulting to the settings for the `main` branch (this covers `alpha` and `beta`)
[build]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vitepress/dist"
  environment = { NODE_VERSION = "18.12.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }

# ##############################
# 'legacy' branch
# ##############################

# 'legacy' branch context
[context.legacy]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vitepress/dist"
  environment = { NODE_VERSION = "18.12.1", YARN_FLAGS="--frozen-lockfile --ignore-optional" }
