# Settings in the [build] context are global and are applied to all contexts
# unless otherwise overridden by more specific contexts.
[build]
  base = "/"
  command = "yarn build:styles && yarn docs:build"
  publish = "docs/.vuepress/dist"

# Add different build command for 'next' branch
[context.next]
  base = "/"
  command = "yarn docs:build"
  publish = "docs/.vuepress/dist"
