/* eslint-disable vue/one-component-per-file -- Component export names are catalog data, not Vue definitions. */
import type { ComponentCatalogDefinition } from './types'

const component = (
  slug: string,
  title: string,
  exports: string[],
  typeFile?: string,
  options: Partial<Pick<ComponentCatalogDefinition, 'aliases' | 'deprecated' | 'sourceDirectories'>> = {},
): ComponentCatalogDefinition => ({
  slug,
  title,
  docPath: `/components/${slug}`,
  exports,
  sourceDirectories: options.sourceDirectories ?? [`src/components/${exports[0]}`],
  typeFiles: typeFile ? [`src/types/${typeFile}.ts`] : [],
  aliases: options.aliases ?? [],
  deprecated: options.deprecated,
})

export const COMPONENT_CATALOG: ComponentCatalogDefinition[] = [
  component('alert', 'Alert', ['KAlert'], 'alert'),
  component('badge', 'Badge', ['KBadge'], 'badge'),
  component('breadcrumbs', 'Breadcrumbs', ['KBreadcrumbs'], 'breadcrumbs'),
  component('button', 'Button', ['KButton'], 'button'),
  component('card', 'Card', ['KCard'], 'card'),
  component('catalog', 'Catalog', ['KCatalog', 'KCatalogItem'], 'catalog'),
  component('checkbox', 'Checkbox', ['KCheckbox'], 'checkbox'),
  component('codeblock', 'CodeBlock', ['KCodeBlock', 'KCodeBlockIconButton'], 'code-block', { aliases: ['Code Block'] }),
  component('collapse', 'Collapse', ['KCollapse'], 'collapse'),
  component('copy', 'Copy', ['KCopy'], 'copy'),
  component('datetime-picker', 'DateTime Picker', ['KDateTimePicker'], 'date-time-picker'),
  component('dropdown', 'Dropdown', ['KDropdown', 'KDropdownItem'], 'dropdown'),
  component('empty-state', 'Empty State', ['KEmptyState'], 'empty-state'),
  component('external-link', 'External Link', ['KExternalLink'], 'external-link'),
  component('file-upload', 'File Upload', ['KFileUpload'], 'file-upload'),
  component('filter-group', 'Filter Group', ['KFilterGroup'], 'filter-group'),
  component('input', 'Input', ['KInput'], 'input'),
  component('input-switch', 'Input Switch', ['KInputSwitch'], 'input-switch'),
  component('label', 'Label', ['KLabel'], 'label'),
  component('modal', 'Modal', ['KModal'], 'modal'),
  component('multiselect', 'Multiselect', ['KMultiselect'], 'multi-select', { aliases: ['Multi Select'] }),
  component('pagination', 'Pagination', ['KPagination'], 'pagination'),
  component('popover', 'Popover', ['KPop'], 'popover', { aliases: ['KPopover', 'Pop'] }),
  component('prompt', 'Prompt', ['KPrompt'], 'prompt'),
  component('radio', 'Radio', ['KRadio'], 'radio'),
  component('renderless/clipboard-provider', 'Clipboard Provider', ['KClipboardProvider'], 'clipboard-provider'),
  component('renderless/k-component', 'KComponent', ['KComponent'], undefined),
  component('renderless/toggle', 'Toggle', ['KToggle'], 'toggle'),
  component('segmented-control', 'Segmented Control', ['KSegmentedControl'], 'segmented-control'),
  component('select', 'Select', ['KSelect'], 'select'),
  component('skeleton', 'Skeleton', ['KSkeleton', 'KSkeletonBox'], 'skeleton'),
  component('slideout', 'Slideout', ['KSlideout'], 'slideout'),
  component('slider', 'Slider', ['KSlider'], 'slider'),
  component('stepper', 'Stepper', ['KStepper'], 'stepper'),
  component('table-data', 'Table Data', ['KTableData'], 'table'),
  component('table-view', 'Table View', ['KTableView'], 'table'),
  component('table', 'Table', ['KTable'], 'table', { deprecated: true }),
  component('tabs', 'Tabs', ['KTabs'], 'tabs'),
  component('textarea', 'TextArea', ['KTextArea'], 'text-area', { aliases: ['Textarea', 'Text Area'] }),
  component('theme-provider', 'Theme Provider', ['KThemeProvider'], 'theme'),
  component('toaster', 'Toaster', ['KToaster', 'ToastManager'], 'toaster'),
  component('tooltip', 'Tooltip', ['KTooltip'], 'tooltip'),
  component('tree-list', 'Tree List', ['KTreeList'], 'tree-list'),
  component('truncate', 'Truncate', ['KTruncate'], 'truncate'),
]
