import type { RouteRecordRaw } from 'vue-router'

const componentRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    name: 'home',
    alias: '/:pathMatch(.*)*',
    meta: { title: 'Kongponents Sandbox' },
    component: () => import('../pages/HomePage.vue'),
  },
  {
    path: '/alert',
    name: 'alert',
    meta: { title: 'Alert Sandbox' },
    component: () => import('../pages/SandboxAlert.vue'),
  },
  {
    path: '/badge',
    name: 'badge',
    meta: { title: 'Badge Sandbox' },
    component: () => import('../pages/SandboxBadge.vue'),
  },
  {
    path: '/button',
    name: 'button',
    meta: { title: 'Button Sandbox' },
    component: () => import('../pages/SandboxButton.vue'),
  },
  {
    path: '/breadcrumbs',
    name: 'breadcrumbs',
    meta: { title: 'Breadcrumbs Sandbox' },
    component: () => import('../pages/SandboxBreadcrumbs.vue'),
  },
  {
    path: '/card',
    name: 'card',
    meta: { title: 'Card Sandbox' },
    component: () => import('../pages/SandboxCard.vue'),
  },
  {
    path: '/catalog',
    name: 'catalog',
    meta: { title: 'Catalog Sandbox' },
    component: () => import('../pages/SandboxCatalog.vue'),
  },
  {
    path: '/checkbox',
    name: 'checkbox',
    meta: { title: 'Checkbox Sandbox' },
    component: () => import('../pages/SandboxCheckbox.vue'),
  },
  {
    path: '/codeblock',
    name: 'codeblock',
    meta: { title: 'Code Block Sandbox' },
    component: () => import('../pages/SandboxCodeBlock.vue'),
  },
  {
    path: '/collapse',
    name: 'collapse',
    meta: { title: 'Collapse Sandbox' },
    component: () => import('../pages/SandboxCollapse.vue'),
  },
  {
    path: '/copy',
    name: 'copy',
    meta: { title: 'Copy Sandbox' },
    component: () => import('../pages/SandboxCopy.vue'),
  },
  {
    path: '/datetimepicker',
    name: 'datetimepicker',
    meta: { title: 'Date Time Picker Sandbox' },
    component: () => import('../pages/SandboxDateTimePicker.vue'),
  },
  {
    path: '/dropdown',
    name: 'dropdown',
    meta: { title: 'Dropdown Sandbox' },
    component: () => import('../pages/SandboxDropdown.vue'),
  },
  {
    path: '/emptystate',
    name: 'emptystate',
    meta: { title: 'Empty State Sandbox' },
    component: () => import('../pages/SandboxEmptyState.vue'),
  },
  {
    path: '/fileupload',
    name: 'fileupload',
    meta: { title: 'File Upload Sandbox' },
    component: () => import('../pages/SandboxFileUpload.vue'),
  },
  {
    path: '/input',
    name: 'input',
    meta: { title: 'Input Sandbox' },
    component: () => import('../pages/SandboxInput.vue'),
  },
  {
    path: '/inputswitch',
    name: 'inputswitch',
    meta: { title: 'Input Switch Sandbox' },
    component: () => import('../pages/SandboxInputSwitch.vue'),
  },
  {
    path: '/label',
    name: 'label',
    meta: { title: 'Label Sandbox' },
    component: () => import('../pages/SandboxLabel.vue'),
  },
  {
    path: '/modals',
    name: 'modals',
    meta: { title: 'Modals Sandbox' },
    component: () => import('../pages/SandboxModals.vue'),
  },
  {
    path: '/multiselect',
    name: 'multiselect',
    meta: { title: 'Multiselect Sandbox' },
    component: () => import('../pages/SandboxMultiselect.vue'),
  },
  {
    path: '/pagination',
    name: 'pagination',
    meta: { title: 'Pagination Sandbox' },
    component: () => import('../pages/SandboxPagination.vue'),
  },
  {
    path: '/pop',
    name: 'pop',
    meta: { title: 'Pop Sandbox' },
    component: () => import('../pages/SandboxPop.vue'),
  },
  {
    path: '/radio',
    name: 'radio',
    meta: { title: 'Radio Sandbox' },
    component: () => import('../pages/SandboxRadio.vue'),
  },
  {
    path: '/segmentedcontrol',
    name: 'segmentedcontrol',
    meta: { title: 'Segmented Control Sandbox' },
    component: () => import('../pages/SandboxSegmentedControl.vue'),
  },
  {
    path: '/select',
    name: 'select',
    meta: { title: 'Select Sandbox' },
    component: () => import('../pages/SandboxSelect.vue'),
  },
  {
    path: '/skeleton',
    name: 'skeleton',
    meta: { title: 'Skeleton Sandbox' },
    component: () => import('../pages/SandboxSkeleton.vue'),
  },
  {
    path: '/slideout',
    name: 'slideout',
    meta: { title: 'Slideout Sandbox' },
    component: () => import('../pages/SandboxSlideout.vue'),
  },
  {
    path: '/stepper',
    name: 'stepper',
    meta: { title: 'Stepper Sandbox' },
    component: () => import('../pages/SandboxStepper.vue'),
  },
  {
    path: '/data-table',
    name: 'data-table',
    meta: { title: 'Data Table Sandbox' },
    component: () => import('../pages/SandboxDataTable.vue'),
  },
  {
    path: '/table',
    name: 'table',
    meta: { title: 'Table Sandbox' },
    component: () => import('../pages/SandboxTable/SandboxTable.vue'),
  },
  {
    path: '/tabs',
    name: 'tabs',
    meta: { title: 'Tabs Sandbox' },
    component: () => import('../pages/SandboxTabs.vue'),
  },
  {
    path: '/textarea',
    name: 'textarea',
    meta: { title: 'Textarea Sandbox' },
    component: () => import('../pages/SandboxTextarea.vue'),
  },
  {
    path: '/toaster',
    name: 'toaster',
    meta: { title: 'Toaster Sandbox' },
    component: () => import('../pages/SandboxToaster.vue'),
  },
  {
    path: '/treelist',
    name: 'treelist',
    meta: { title: 'Tree List Sandbox' },
    component: () => import('../pages/SandboxTreeList.vue'),
  },
]

export default componentRoutes
