---
name: Renovate Bot dependency updates auto-merge

permissions:
  pull-requests: write
  contents: write

on: pull_request_target

jobs:
  renovate-autoapprove:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          # Use the bot account PAT to allow auto-approve and merge the PRs
          GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
