name: Get Changed files

on:
  workflow_call:
    outputs:
      component-files-changed:
        description: Check if component (`src` directory) files have changed
        value: ${{ jobs.get-changed-files.outputs.component-files-changed }}
      docs-files-changed:
        description: Check if docs (`docs` directory) files have changed
        value: ${{ jobs.get-changed-files.outputs.docs-files-changed }}
      components-or-docs-or-cypress-files-changed:
        description: Check if src or docs (`src` or `docs` directories) files have changed
        value: ${{ jobs.get-changed-files.outputs.components-or-docs-or-cypress-files-changed }}

jobs:
  get-changed-files:
    name: Check changed files
    runs-on: ubuntu-20.04
    outputs:
      component-files-changed: ${{ steps.component-files-changed.outputs.any_modified }}
      docs-files-changed: ${{ steps.docs-files-changed.outputs.any_modified }}
      components-or-docs-or-cypress-files-changed: ${{ steps.components-or-docs-or-cypress-files-changed.outputs.any_modified }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Check if component (`src` directory) files have changed
        uses: tj-actions/changed-files@v34
        id: component-files-changed
        # Return 'true' for any directories listed here that changed
        with:
          files: |
            src/**

      - name: Check if docs (`docs` directory) files have changed
        uses: tj-actions/changed-files@v34
        id: docs-files-changed
        # Return 'true' for any directories listed here that changed
        with:
          files: |
            docs/**

      - name: Check if files changed in `src/`, `docs/`, or `cypress/` directories
        uses: tj-actions/changed-files@v34
        id: components-or-docs-or-cypress-files-changed
        # Return 'true' for any directories listed here that changed
        with:
          files: |
            src/**
            docs/**
            cypress/**
