name: PR Audit
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - edited

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-audit:
    name: Audit
    permissions:
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{  secrets.KONGPONENTS_BOT_PAT }}

    steps:

      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-pnpm-with-dependencies/

      - name: PR Audit
        if: github.actor != 'renovate[bot]'
        uses: Kong/public-shared-actions/pr-previews/audit@cbbbf31a69c4f38d1803ededb69acb2a86836f85
        with:
          renovate-pr-author: renovate[bot]
