name: Publish

on:
  push:
    branches:
      - main

jobs:
  get-changed-files:
    name: Get Changed Files
    uses: ./.github/workflows/get-changed-files.yml

  run-tests:
    name: Tests
    needs:
      - get-changed-files
    uses: ./.github/workflows/test.yml
    secrets:
      # Skip running the Docs visual regression tests since we update the snapshots on publish
      SKIP_VISUAL_REGRESSION_TESTS: 'true'

  publish:
      name: Build and Publish Kongponents
      needs:
        - get-changed-files
        - run-tests
      # Only run the publish action (including semantic-release) if files in the /src/ directory changed.
      # Should only run if files in the `src/` directory were changed
      if: needs.get-changed-files.outputs.component-files-changed == 'true'
      runs-on: ubuntu-latest
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            token: ${{ secrets.KONGPONENTS_BOT_PAT }}

        - name: setup git
          run: |
            git config --global user.name 'kongponents-bot'
            git config --global user.email '95302551+kongponents-bot@users.noreply.github.com'

        - name: Create .npmrc
          run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

        - name: Use Node.js
          uses: actions/setup-node@v3
          with:
            node-version-file: '.nvmrc'

        - name: Install dependencies
          run: yarn install --frozen-lockfile
          env:
            NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

        - name: Build
          run: yarn build:kongponents

        - name: Update Cypress visual regression snapshots for docs site
          if: needs.get-changed-files.outputs.components-or-docs-or-cypress-files-changed == 'true'
          uses: cypress-io/github-action@v4
          with:
            install: false
            browser: chrome
            command: yarn test:e2e:update-snapshots

        - name: Commit new visual regression snapshots
          if: needs.get-changed-files.outputs.components-or-docs-or-cypress-files-changed == 'true'
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: 'test(e2e): update visual regression snapshots'
            file_pattern: 'docs/tests/e2e/snapshots/**/*'
            commit_user_name: 'kongponents-bot'
            commit_user_email: 'konnectx-engineers+kongponents-bot@konghq.com'

        - name: Semantic Release
          uses: cycjimmy/semantic-release-action@v3
          env:
            # Since branch protections are on (pushing commits) you need to use a bot PAT
            GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}

  no-tests-required:
    name: No Component Tests needed
    needs:
      - get-changed-files
    if: needs.get-changed-files.outputs.component-files-changed == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip component tests
        run: echo "No files changed in the `src/`, `docs/`, or `cypress/` directories, so no tests are needed."

  no-publish-required:
    name: No Build and Publish needed
    needs:
      - get-changed-files
    if: needs.get-changed-files.outputs.components-or-docs-or-cypress-files-changed == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip new release
        run: echo "No files changed in the `src/` directory, so no new release is required."
