name: Publish

on:
  push:
    branches:
    - master
    - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: install and lint
      run: |
        yarn
        yarn lint

    - name: test
      run: |
        yarn test-coverage

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: visual-regression-test
      run: |
        yarn build
        npx percy snapshot docs/.vuepress/dist/ --ignore-files "**/404.html"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          token: ${{ secrets.KONGPONENTS_BOT_PAT }}

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: setup git
      run: |
        git config --global user.name 'kongponents-bot'
        git config --global user.email '95302551+kongponents-bot@users.noreply.github.com'

    - name: install
      run: |
        npm config set scripts-prepend-node-path true
        npm config set "//registry.npmjs.org/:_authToken" "$NPM_AUTH_TOKEN" -g
        yarn install
      env:
        NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

    - name: yarn build
      run: |
        yarn build
    - name: publish
      run: |
        yarn lerna bootstrap
        yarn publish:ci
      env:
        # lerna uses GH_TOKEN to init it's gh lib
        GH_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
