name: Publish

on:
  push:
    branches:
    - master
    - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install and lint
      run: |
        yarn
        yarn lint
    - name: test
      run: |
        yarn test-coverage
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
    - name: visual-regression-test
      run: |
        yarn build
        npx percy snapshot docs/.vuepress/dist/ --ignore-files "**/404.html"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: setup git
      run: |
        git config --global user.name 'kongponents'
        git config --global user.email 'npm@konghq.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout ${{ github.ref }}

    - name: install
      run: |
        npm config set scripts-prepend-node-path true
        npm config set "//registry.npmjs.org/:_authToken" "$NPM_AUTH_TOKEN" -g
        yarn install
      env:
        NPM_AUTH_TOKEN: ${{ secrets.YARN_TOKEN }}

    - name: yarn build
      run: |
        yarn build
    - name: publish
      run: |
        yarn lerna bootstrap
        yarn publish:ci
