name: Build & Run Tests

on:
  pull_request:
    branches:
    - master
    - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1
    - name: Read .nvmrc
       run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'
    - name: install, lint
      run: |
        yarn install
        yarn lint
    - name: build
      run: |
        yarn build
    - name: test
      run: |
        yarn test
    - name: visual-regression-test
      run: |
        npx percy snapshot docs/.vuepress/dist/ --ignore-files "**/404.html"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
