name: Build & Run Tests

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [14.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }} 
    - name: install, lint
      run: |
        yarn install
        yarn lint
    - name: build
      run: |
        yarn build
    - name: test
      run: |
        yarn test
    - name: visual-regression-test
      run: |
        npx percy snapshot docs/.vuepress/dist/ --ignore-files "**/404.html"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    - name: Run Lighthouse against a static dist dir
      uses: treosh/lighthouse-ci-action@v8
      with:
        # no urls needed, since it uses local folder to scan .html files
        configPath: './lighthouserc.json'
