name: Build & Run Tests

on:
  pull_request:
    branches:
    - master

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/run-test
    # - uses: actions/checkout@v1
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - name: install and lint
    #   run: |
    #     yarn
    #     yarn lint
    # - name: test
    #   run: |
    #     yarn test
