name: Build & Run Tests

on:
  pull_request:
    branches:
    - main
    - 'release/**'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v1

    - name: Read .nvmrc
      run: echo ::set-output name=NVMRC::$(cat .nvmrc)
      id: nvm

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '${{ steps.nvm.outputs.NVMRC }}'

    - name: install, lint
      run: |
        yarn install
        yarn lint

    - name: build
      run: |
        yarn build

    - name: test
      run: |
        yarn test

    - name: Trigger Percy visual regression test for docs
      timeout-minutes: 5
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
        PERCY_TARGET_BRANCH: main
      run: |
        npx @percy/cli snapshot docs/.vuepress/dist/ --exclude "**/404.html"
