name: Build & Run Tests

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x, 14.x, 16.x]
        include:
          - node: 16.x
            experimental: true
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }} 
    - name: install, lint
      run: |
        yarn install
        yarn lint
    - name: build
      run: |
        yarn build
    - name: test
      run: |
        yarn test
